---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - custom

steps:
  - name: lint
    image: docker:dind
    commands:
      - apk update
      - apk add bash make python3 py3-pip
      - make install-pip
      - export PATH="$$HOME/.local/bin:$$PATH"
      - make lint
