---
version: "2.1"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "${TESSERACT_UID}:${TESSERACT_GID}"
    restart: always
    ports:
      - "4533:4533"
    environment:
      ND_MUSICFOLDER: "/music"
      ND_DATAFOLDER: "/data"
      ND_SCANINTERVAL: "12h"
      ND_LOGLEVEL: "info"
      ND_PORT: 4533
      ND_TRANSCODINGCACHESIZE: "100MB"
      ND_SESSIONTIMEOUT: "24h"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_SPOTIFY_ID: "${TESSERACT_SPOTIFY_ID}"
      ND_SPOTIFY_SECRET: "${TESSERACT_SPOTIFY_SECRET}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/navidrome_data:/data"
      - "${TESSERACT_DATA_PATH}/Music:/music:ro"
