---

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
      OPENVPN_PROVIDER: "CUSTOM"
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      LOCAL_NETWORK: "192.168.1.0/24"
      #TRANSMISSION_WEB_UI: transmission-web-control
      TRANSMISSION_HOME: "/config"
      TRANSMISSION_WATCH_DIR_ENABLED: "false"
      #TRANSMISSION_WATCH_DIR: "/config/transmission/watch"
      TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED: "false"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "10"
      TRANSMISSION_IDLE_SEEDING_LIMIT: "1320" # 22 hours
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT: "2"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_QUEUE_STALLED_ENABLED: "true"
      TRANSMISSION_QUEUE_STALLED_MINUTES: "30"
    volumes:
      - ${TESSERACT_APPDATA_PATH}/transmission_config:/config
      - ${TESSERACT_APPDATA_PATH}/transmission_openvpn_config:/etc/openvpn/custom/
      - transmission_cache:/data

volumes:
  transmission_cache:
