---

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: always
    ports:
      - 5055:5055
    environment:
      LOG_LEVEL: debug
      TZ: "${TESSERACT_TZ}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/jellyseerr_config:/app/config"
