---

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: always
    ports:
      - "3004:8080"
    environment:
      OLLAMA_BASE_URL: "https://ai.${TESSERACT_DOMAIN}"
      WEBUI_URL: "https://chat.${TESSERACT_DOMAIN}"
      CORS_ALLOW_ORIGIN: "https://chat.${TESSERACT_DOMAIN}"
      ENABLE_OPENAI_API: False
      ENABLE_EVALUATION_ARENA_MODELS: False
      ENABLE_COMMUNITY_SHARING: False
      ENABLE_MESSAGE_RATING: False
      ENABLE_AUTOCOMPLETE_GENERATION: False
      ENABLE_FOLLOW_UP_GENERATION: False
      ENABLE_WEB_SEARCH: True
      WEB_SEARCH_RESULT_COUNT: 6
      WEB_SEARCH_ENGINE: searxng
      SEARXNG_QUERY_URL: "https://search.${TESSERACT_DOMAIN}/search?q=<query>"

    volumes:
      - "${TESSERACT_APPDATA_PATH}/openwebui-data:/app/backend/data"
