---
version: "2.1"

services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: always
    #ports:
      #- "80:8080"
    environment:
      PUID: ${TESSERACT_UID}
      PGID: ${TESSERACT_GID}
      TZ: "${TESSERACT_TZ}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/heimdall_config:/config"
