---

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    ports:
      - 8686:8686
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
      TESSERACT_MODS: linuxserver/mods:lidarr-flac2mp3
    volumes:
      - "${TESSERACT_APPDATA_PATH}/lidarr_config:/config"
      - "${TESSERACT_DATA_PATH}/Music:/music"
      - "${TESSERACT_DATA_PATH}/Downloads/completed:/downloads"
