---

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.11.0
    container_name: jellyfin
    restart: always
    ports:
      - 8096:8096 # UI
      - 7359:7359/udp # optional
      # - 1900:1900/udp # optional DLNA
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
    devices:
      - /dev/dri:/dev/dri  # vaapi encoding
    volumes:
      - "${TESSERACT_APPDATA_PATH}/jellyfin_config:/config"
      - "${TESSERACT_DATA_PATH}/Tvshows:/data/tvshows:ro"
      - "${TESSERACT_DATA_PATH}/Movies:/data/movies:ro"
