---
version: "2.1"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    container_name: coder
    restart: always
    ports:
      - "7080:7080"
    group_add:
      - "${TESSERACT_DOCKER_GROUP}" # docker group on host
    environment:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "http://code.${TESSERACT_DOMAIN}"
      CODER_DATA: "$HOME/.config/coderv2-docker"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/coder_config:/home/coder/.config"
      - /var/run/docker.sock:/var/run/docker.sock
