---
version: "2.1"

services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr
    container_name: wizarr
    restart: always
    ports:
      - 5690:5690
    environment:
      TZ: "${DOCKER_TZ}"
      APP_URL: "https://wiz.${DOCKER_DOMAIN}"
      DISABLE_BUILTIN_AUTH: "false"
    volumes:
      - "${DOCKER_APPDATA_PATH}/wizarr_config:/data/database"
