---
version: "2.1"

services:
  searx:
    image: searxng/searxng:latest
    container_name: searx
    restart: always
    ports:
      - 8080:8080
    environment:
      INSTANCE_NAME: Searx
      BASE_URL: "https://search.${TESSERACT_DOMAIN}"
      AUTOCOMPLETE: duckduckgo
    volumes:
      - "${TESSERACT_APPDATA_PATH}/searx_config:/etc/searx"
      - "${TESSERACT_APPDATA_PATH}/searx_icons:/usr/local/searxng/searx/static/themes/simple/img"
