---
version: "2.1"

services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: always
    command: [ "start.sh", "immich" ]
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_db
      DB_USERNAME: immich_user
      DB_PASSWORD: ${TESSERACT_SQL_PASSWORD}
      DB_DATABASE_NAME: immich_database
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      LOG_LEVEL: simple
      JWT_SECRET: "${TESSERACT_IMMICH_JWT_SECRET}"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
      IMMICH_MACHINE_LEARNING_URL: "http://immich_ml:3003"
      TYPESENSE_API_KEY: "${TESSERACT_TYPESENSE_API_KEY}"
      TYPESENSE_HOST: immich_typesense
    depends_on:
      - immich_redis
      - immich_db
      - immich_typesense
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TESSERACT_DATA_PATH}/Immich:/usr/src/app/upload

  immich_microservices:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_microservices
    restart: always
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_db
      DB_USERNAME: immich_user
      DB_PASSWORD: ${TESSERACT_SQL_PASSWORD}
      DB_DATABASE_NAME: immich_database
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      LOG_LEVEL: simple
      JWT_SECRET: "${TESSERACT_IMMICH_JWT_SECRET}"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
      IMMICH_MACHINE_LEARNING_URL: "http://immich_ml:3003"
      TYPESENSE_API_KEY: "${TESSERACT_TYPESENSE_API_KEY}"
      TYPESENSE_HOST: immich_typesense
    depends_on:
      - immich_redis
      - immich_db
      - immich_typesense
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TESSERACT_DATA_PATH}/Immich:/usr/src/app/upload

  immich_ml:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_ml
    restart: always
    volumes:
      - ${TESSERACT_APPDATA_PATH}/immich_upload:/usr/src/app/upload
      - ${TESSERACT_DATA_PATH}/Immich/library:/usr/src/app/upload/library
      - immich_ml_cache:/cache

  immich_web:
    image: ghcr.io/immich-app/immich-web:release
    container_name: immich_web
    restart: always
    environment:
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      LOG_LEVEL: simple
      JWT_SECRET: "${TESSERACT_IMMICH_JWT_SECRET}"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
      IMMICH_SERVER_URL: "http://immich_server:3001"

  immich_proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    restart: always
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich_server
    environment:
      IMMICH_SERVER_URL: "http://immich_server:3001"
      IMMICH_WEB_URL: "http://immich_web:3000"

  immich_redis:
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    container_name: immich_redis
    restart: always

  immich_db:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${TESSERACT_SQL_PASSWORD}
      POSTGRES_USER: immich_user
      POSTGRES_DB: immich_database
    volumes:
      - ${TESSERACT_APPDATA_PATH}/immich_db:/var/lib/postgresql/data

  immich_typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1
    restart: always
    environment:
      TYPESENSE_API_KEY: "${TESSERACT_TYPESENSE_API_KEY}"
      TYPESENSE_DATA_DIR: "/data"
    logging:
      driver: none
    volumes:
      - ${TESSERACT_APPDATA_PATH}/immich_typesense:/data

volumes:
  immich_ml_cache:
