---

services:
  autoscan:
    image: cloudb0x/autoscan:latest
    container_name: autoscan
    restart: always
    ports:
      - 3030:3030
    environment:
      PUID: ${TESSERACT_UID}
      PGID: ${TESSERACT_GID}
    volumes:
      - "${TESSERACT_APPDATA_PATH}/autoscan_config:/config"
      - "${TESSERACT_DATA_PATH}/Movies:/media/movies"
      - "${TESSERACT_DATA_PATH}/Tvshows:/media/tvshows"
