---
version: "2.1"

services:
  drone:
    image: drone/drone:latest
    container_name: drone
    restart: always
    ports:
      - 8005:80
    environment:
      DRONE_SERVER_HOST: "drone.${TESSERACT_DOMAIN}"
      DRONE_SERVER_PROTO: http

      DRONE_USER_CREATE: "username:${TESSERACT_DOCKER_USERNAME},admin:true"

      DRONE_GITEA_SERVER: "http://git.${TESSERACT_DOMAIN}"
      DRONE_GITEA_CLIENT_ID: "${TESSERACT_GITEA_CLIENT_ID}"
      DRONE_GITEA_CLIENT_SECRET: "${TESSERACT_GITEA_CLIENT_SECRET}"
      DRONE_RPC_SECRET: "${TESSERACT_DRONE_SECRET}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${TESSERACT_APPDATA_PATH}/drone_data:/var/lib/drone"

  drone-runner-docker:
    image: drone/drone-runner-docker:latest
    container_name: drone-runner-docker
    restart: always
    ports:
      - 3005:3000
    environment:
      DRONE_RPC_HOST: "drone.${TESSERACT_DOMAIN}"
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: "${TESSERACT_DRONE_SECRET}"
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
