---
version: "2.1"

services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    restart: always
    ports:
      - 8098:8080
    depends_on:
      - romm_db
    environment:
      DB_HOST: romm_db
      DB_NAME: romm_database
      DB_USER: romm_user
      DB_PASSWD: "${DOCKER_SQL_PASSWORD}"
      IGDB_CLIENT_ID: "${DOCKER_IGDB_CLIENT_ID}"
      IGDB_CLIENT_SECRET: "${DOCKER_IGDB_CLIENT_SECRET}"
      ROMM_AUTH_SECRET_KEY: "${DOCKER_ROMM_AUTH_SECRET_KEY}"
      ROMM_AUTH_USERNAME: "${DOCKER_DOCKER_USERNAME}"
      ROMM_AUTH_PASSWORD: "${DOCKER_DOCKER_PASSWORD}"
    volumes:
      - "${DOCKER_APPDATA_PATH}/romm_data:/romm"
      - "${DOCKER_DATA_PATH}/Games/ROMs:/romm/library"

  romm_db:
    image: mariadb:latest
    container_name: romm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DOCKER_SQL_PASSWORD}"
      MYSQL_DATABASE: romm_database
      MYSQL_USER: romm_user
      MYSQL_PASSWORD: "${DOCKER_SQL_PASSWORD}"
    volumes:
      - "${DOCKER_APPDATA_PATH}/romm_db:/var/lib/mysql"
