---

services:
  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    restart: always
    ports:
      - 8899:8888
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
    devices:
      - /dev/dri:/dev/dri       # For H/W transcoding using the VAAPI encoder
    volumes:
      - "${TESSERACT_APPDATA_PATH}/unmanic_config:/config"
      - unmanic_cache:/tmp/unmanic
      - stash:/library/stash

volumes:
  unmanic_cache:
  stash:
    driver: local
    driver_opts:
      type: cifs
      device: //${TESSERACT_TEPIG_HOST}/Stash
      o: "username=${TESSERACT_TEPIG_USERNAME},\
        password=${TESSERACT_TEPIG_PASSWORD},\
        uid=${TESSERACT_UID},\
        gid=${TESSERACT_GID},\
        vers=3.0,\
        file_mode=0660,\
        dir_mode=0770,\
        rw"
