---

services:
  openhands:
    image: docker.openhands.dev/openhands/openhands:1.6
    container_name: openhands
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      AGENT_SERVER_IMAGE_REPOSITORY: "ghcr.io/openhands/agent-server"
      AGENT_SERVER_IMAGE_TAG: "1.15.0-python"
      LOG_ALL_EVENTS: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${TESSERACT_APPDATA_PATH}/openhands_data:/.openhands"
