---
version: "2.1"

services:
  drone:
    image: drone/drone:latest
    container_name: drone
    restart: always
    ports:
      - 8005:80
    environment:
      DRONE_SERVER_HOST: "drone.${DOCKER_DOMAIN}"
      DRONE_SERVER_PROTO: http

      DRONE_USER_CREATE: "username:${DOCKER_DOCKER_USERNAME},admin:true"

      DRONE_GITEA_SERVER: "http://git.${DOCKER_DOMAIN}"
      DRONE_GITEA_CLIENT_ID: "${DOCKER_GITEA_CLIENT_ID}"
      DRONE_GITEA_CLIENT_SECRET: "${DOCKER_GITEA_CLIENT_SECRET}"
      DRONE_RPC_SECRET: "${DOCKER_DRONE_SECRET}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DOCKER_APPDATA_PATH}/drone_data:/var/lib/drone"
