---

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: always
    ports:
      - 8098:8080
    depends_on:
      - romm_db
    environment:
      DB_HOST: romm_db
      DB_NAME: romm_database
      DB_USER: romm_user
      DB_PASSWD: "${TESSERACT_SQL_PASSWORD}"
      ROMM_AUTH_SECRET_KEY: "${TESSERACT_ROMM_AUTH_SECRET_KEY}"
      # IGDB_CLIENT_ID: "${TESSERACT_IGDB_CLIENT_ID}"
      # IGDB_CLIENT_SECRET: "${TESSERACT_IGDB_CLIENT_SECRET}"
      # MOBYGAMES_API_KEY: "${TESSERACT_MOBYGAMES_API_KEY}"
      # STEAMGRIDDB_API_KEY: "${TESSERACT_STEAMGRIDDB_API_KEY}"

    volumes:
      - "${TESSERACT_DATA_PATH}/Games/ROMs:/romm/library"
      - "${TESSERACT_APPDATA_PATH}/romm_resources:/romm/resources"
      - "${TESSERACT_APPDATA_PATH}/romm_config:/romm/config"
      - "${TESSERACT_APPDATA_PATH}/romm_assets:/romm/assets"
      - romm_cache:/redis-data

  romm_db:
    image: mariadb:latest
    container_name: romm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${TESSERACT_SQL_PASSWORD}"
      MYSQL_DATABASE: romm_database
      MYSQL_USER: romm_user
      MYSQL_PASSWORD: "${TESSERACT_SQL_PASSWORD}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/romm_db:/var/lib/mysql"

volumes:
  romm_cache:
