---
version: '2.1'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    user: root
    ports:
      - 8083:8080
      - 50000:50000
    environment:
      JENKINS_JAVA_OPTS: "-Dhudson.util.ProcessTree.disable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TESSERACT_APPDATA_PATH}/jenkins_config:/var/jenkins_home
