---

version: "2.1"

services:
  code-server:
    # should use codercom/code-server:latest
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: always
    ports:
      - 8443:8443
    environment:
      PUID: ${DOCKER_UID}
      PGID: ${DOCKER_GID}
      TZ: ${DOCKER_TZ}
      # PASSWORD: password #optional
      # HASHED_PASSWORD:  #optional
      SUDO_PASSWORD: ${DOCKER_DOCKER_PASSWORD}
      # SUDO_PASSWORD_HASH:  #optional
      # PROXY_DOMAIN: code-server.my.domain #optional
      DEFAULT_WORKSPACE: /workspace #optional
    volumes:
      - ${DOCKER_APPDATA_PATH}/code-server_config:/config
      - /home/${DOCKER_USERNAME}/workspace:/workspace
