---
version: '2.1'

services:
  searx:
    image: searx/searx:latest
    container_name: searx
    restart: always
    ports:
      - '8080:8080'
    environment:
      - BASE_URL=http://192.168.1.6:8080/
      #- BIND_ADDRESS=0.0.0.0:8080
      #- MORTY_URL=http://192.168.1.xx/morty/
      #- MORTY_KEY=KEY
    volumes:
      - ${TES_APPDATA_PATH}/searx_config:/etc/searx
