---

services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep
    restart: always
    ports:
      - 3000:3000
    environment:
      KARAKEEP_VERSION: release
      DATA_DIR: /data
      CRAWLER_FULL_PAGE_SCREENSHOT: "true"
      CRAWLER_FULL_PAGE_ARCHIVE: "true"
      MAX_ASSET_SIZE_MB: 25
      CRAWLER_NUM_WORKERS: 2
      NEXTAUTH_SECRET: "${TESSERACT_KARAKEEP_SECRET}"
      NEXTAUTH_URL: "http://charizard.${TESSERACT_DOMAIN}:3000"
      REDIS_HOST: karakeep-redis
      MEILI_ADDR: http://karakeep-meilisearch:7700
      MEILI_MASTER_KEY: "${TESSERACT_KARAKEEP_SECRET}"
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      OLLAMA_BASE_URL: "https://ai.${TESSERACT_DOMAIN}"
      INFERENCE_TEXT_MODEL: "llama3.1"
      INFERENCE_IMAGE_MODEL: "llava:13b"
      INFERENCE_JOB_TIMEOUT_SEC: "300"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/karakeep-data:/data"

  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: karakeep-meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "${TESSERACT_KARAKEEP_SECRET}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/karakeep-meilisearch:/meili_data"

  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
