---

services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: always
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 2283:2283
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME: immich_user
      DB_PASSWORD: "${TESSERACT_SQL_PASSWORD}"
      DB_DATABASE_NAME: immich_database
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      IMMICH_MACHINE_LEARNING_URL: "http://immich_ml:3003"
    depends_on:
      - immich_redis
      - immich_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TESSERACT_DATA_PATH}/Immich:/usr/src/app/upload

  immich_ml:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_ml
    restart: always
    volumes:
      - immich_ml_cache:/cache

  immich_redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich_db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    container_name: immich_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "${TESSERACT_SQL_PASSWORD}"
      POSTGRES_USER: immich_user
      POSTGRES_DB: immich_database
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${TESSERACT_APPDATA_PATH}/immich_db:/var/lib/postgresql/data

volumes:
  immich_ml_cache:
