---
version: "2.1"

# docker exec -u 0 languagetool bash -c "if [ ! -d /ngrams/en ]; then cd /ngrams; \
# wget -O /tmp/ngrams.zip 'https://languagetool.org/download/ngram-data/ngrams-en-20150817.zip'; \
# unzip /tmp/ngrams.zip; rm /tmp/ngrams.zip; chown -R 100:101 *; fi"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - 8010:8010
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - languagetool_ngrams:/ngrams

volumes:
  languagetool_ngrams:
