---
version: "2.1"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    ports:
      - 9696:9696
    environment:
      PUID: "${DOCKER_UID}"
      PGID: "${DOCKER_GID}"
      TZ: "${DOCKER_TZ}"
    volumes:
      - "${DOCKER_APPDATA_PATH}/prowlarr_config:/config"
