---

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: host
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
      WEBUI_PORT: 8112
    volumes:
      - "${TESSERACT_APPDATA_PATH}/qbittorrent_config:/config"
      - "${TESSERACT_DATA_PATH}/Downloads/qbittorrent:/downloads"
