---
version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: always
    ports:
      - 9117:9117
    environment:
      PUID: "${TESSERACT_UID}"
      PGID: "${TESSERACT_GID}"
      TZ: "${TESSERACT_TZ}"
      AUTO_UPDATE: "true" #optional
      #RUN_OPTS: <run options here> #optional
    volumes:
      - ${TESSERACT_APPDATA_PATH}/jackett_config:/config
      #- <path to blackhole>:/downloads
