---

# Plugin stack
# Community,Tdarr_Plugin_lmg1_Reorder_Streams,,Community,Tdarr_Plugin_MC93_Migz1FFMPEG_CPU,,Community,Tdarr_Plugin_MC93_Migz5ConvertAudio,,Community,Tdarr_Plugin_MC93_Migz1Remux,,Community,Tdarr_Plugin_MC93_Migz3CleanAudio,,Community,Tdarr_Plugin_MC93_Migz4CleanSubs,,Community,Tdarr_Plugin_MC93_Migz2CleanTitle,,Community,Tdarr_Plugin_MC93_MigzImageRemoval,,

# docker exec tdarr chown -R 1003:1003 /media/cache
# docker exec tdarr-node chown -R 1003:1003 /media/cache

services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:latest
    restart: always
    #network_mode: bridge # Don't like that tdarr uses bridge
    ports:
      - 8265:8265 # webUI port
    #  - 8266:8266 # server port
    #  - 8267:8267 # Internal node port
    environment:
      - TZ=${TESSERACT_TZ}
      - PUID=${TESSERACT_UID}
      - PGID=${TESSERACT_GID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=node1
    devices:
      - /dev/dri:/dev/dri # For H/W transcoding using the VAAPI encoder
    volumes:
      - ${TESSERACT_APPDATA_PATH}/tdarr_server:/app/server
      - ${TESSERACT_APPDATA_PATH}/tdarr_configs:/app/configs
      - ${TESSERACT_APPDATA_PATH}/tdarr_logs:/app/logs

      - tdarr_cache:/temp

      - "${TESSERACT_DATA_PATH}/Tvshows:/tv"
      - "${TESSERACT_DATA_PATH}/Movies:/movies"

volumes:
  tdarr_cache:
