---

version: "2.1"

services:
  code-server:
    # should use codercom/code-server:latest
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: always
    ports:
      - 8443:8443
    environment:
      PUID: ${TESSERACT_UID}
      PGID: ${TESSERACT_GID}
      TZ: ${TESSERACT_TZ}
      # PASSWORD: password #optional
      # HASHED_PASSWORD:  #optional
      SUDO_PASSWORD: ${TESSERACT_DOCKER_PASSWORD}
      # SUDO_PASSWORD_HASH:  #optional
      # PROXY_DOMAIN: code-server.my.domain #optional
      DEFAULT_WORKSPACE: /workspace #optional
    volumes:
      - ${TESSERACT_APPDATA_PATH}/code-server_config:/config
      - /home/${TESSERACT_USERNAME}/workspace:/workspace
