---
version: "2.1"

services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./manga:/manga
      - "${DOCKER_DATA_PATH}/Ebooks:/books"
      - ${DOCKER_APPDATA_PATH}/kavita_config:/kavita/config
