---
version: "2.1"

services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: always
    command: [ "start.sh", "immich" ]
    ports:
      - 2283:3001
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME: immich_user
      DB_PASSWORD: ${DOCKER_SQL_PASSWORD}
      DB_DATABASE_NAME: immich_database
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      IMMICH_MACHINE_LEARNING_URL: "http://immich_ml:3003"
    depends_on:
      - immich_redis
      - immich_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/Immich:/usr/src/app/upload

  immich_microservices:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_microservices
    restart: always
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME: immich_user
      DB_PASSWORD: ${DOCKER_SQL_PASSWORD}
      DB_DATABASE_NAME: immich_database
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: ./upload
      IMMICH_MACHINE_LEARNING_URL: "http://immich_ml:3003"
    depends_on:
      - immich_redis
      - immich_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/Immich:/usr/src/app/upload

  immich_ml:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_ml
    restart: always
    volumes:
      - immich_ml_cache:/cache

  immich_redis:
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    container_name: immich_redis
    restart: always

  immich_db:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DOCKER_SQL_PASSWORD}
      POSTGRES_USER: immich_user
      POSTGRES_DB: immich_database
    volumes:
      - ${DOCKER_APPDATA_PATH}/immich_db:/var/lib/postgresql/data

volumes:
  immich_ml_cache:
