---
version: "2.1"

services:
  autoscan:
    image: cloudb0x/autoscan:latest
    container_name: autoscan
    restart: always
    ports:
      - 3030:3030
    environment:
      PUID: ${DOCKER_UID}
      PGID: ${DOCKER_GID}
    volumes:
      - "${DOCKER_APPDATA_PATH}/autoscan_config:/config"
      - "${DOCKER_DATA_PATH}/Movies:/media/movies"
      - "${DOCKER_DATA_PATH}/Tvshows:/media/tvshows"
