---
version: "2.1"

services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 300   # check every 5 minutes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
